version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      actions:
        update-types: [minor, patch]
  - package-ecosystem: nuget
    directory: /
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      nuget:
        update-types: [minor, patch]
