name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build -c Release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/Release/net7.0-windows/VirtualDesktop.VRCFaceTracking.zip
            bin/Release/net7.0-windows/VirtualDesktop.FaceTracking.dll
            module.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
